spring:
  application:
    name: mycodeBack
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/mycodedb
    username: mycode
    password: qwe321!!

  jpa:
#    hibernate:
#      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  output:
    ansi:
      enabled: always

logging:
  level:
    org:
      springframework:
        security:
          web: TRACE

jwt:
  secretKey: qwe321qwe321qwe321qwe321qwe321qwe321qwe321qwe321qwe321
  access:
    #1일
    expiration: 86400000
  refresh:
    #90일
    expiration: 7776000000